### ISSUE TITLE
ghci memory usage out of control

### ISSUE THREAD

**Issue by miguel-negrao** [dramforever/vscode-ghc-simple#43] opened 2019-09-28 11:37 UTC
## Status

- [ ] A workaround is available
- [ ] A fix is written
- [ ] A fix is released
- [ ] The fixed verison is on the marketplace.

---

- Version of vscode-ghc-simple: 0.1.13
- Version of VSCode: 1.38.1
- Version of Haskell-related tools:
    
    - GHC: 8.0.2
    - Stack:  not using
    - Cabal: 1.24.0.2
- Linux Debian 10
- nix-env: 1.11.8

## Steps to reproduce

Using simple ghc with a simple project ghci will go to 100% CPU usage and memory usage will slowly increase until taking all available RAM. At that point I have to kill ghc. With this issues It becomes impossible to use the plugin.

I would expect ghci memory usage not to continually increase.

My ghc and cabal are provided by nix.  I do not use stack.

**Comment by dramforever** [comment] 2019-09-29 05:10
Very likely a duplicate of #41

**Comment by miguel-negrao** [comment] 2019-09-30 11:58
Note that in my system the plugin remains always responsive, and the floating windows appearing immediately. The high cpu usage doesn't seem to impact responsiveness.

**Comment by dramforever** [comment] 2020-03-29 06:01
If you haven't abandoned this extension please try v0.1.16 and see if the problem is gone. Thanks.

**Comment by dramforever** [comment] 2020-04-08 06:58
Closing in favor of #56, which tracks the problem of GHCi itself leaking memory.

There has been several issue threads with a mixture of problems. I decided that instead of trying to decide which issue corresponds to which problem, I'll just open a new issue for each problem, so I'm closing a few 'discussion threads' and opening a few 'problem threads', which hopefully makes the issue list more focused.

**Closed by dramforever** 2020-04-08 06:58 UTC
